// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOsgqdhaBxqHlh0BpeaHdYGrx-OWGmp0',
    appId: '1:397847296748:web:65b772f6bf57f82c66c3c9',
    messagingSenderId: '397847296748',
    projectId: 'smart-garden-dc114',
    authDomain: 'smart-garden-dc114.firebaseapp.com',
    storageBucket: 'smart-garden-dc114.firebasestorage.app',
    measurementId: 'G-GSZXL1SG0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkz5BkvXVFBcbs5zYFfJ7Mmrg7lzeQwc',
    appId: '1:397847296748:android:4c18169bf7736bb566c3c9',
    messagingSenderId: '397847296748',
    projectId: 'smart-garden-dc114',
    storageBucket: 'smart-garden-dc114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4lpfytkjLcTZc6V1p2AuInzVWLLjFvU',
    appId: '1:397847296748:ios:1ff7f445fae21ded66c3c9',
    messagingSenderId: '397847296748',
    projectId: 'smart-garden-dc114',
    storageBucket: 'smart-garden-dc114.firebasestorage.app',
    iosClientId: '397847296748-vchtmm3q1ul3bpp0jg2v9kcektvlpi0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4lpfytkjLcTZc6V1p2AuInzVWLLjFvU',
    appId: '1:397847296748:ios:1ff7f445fae21ded66c3c9',
    messagingSenderId: '397847296748',
    projectId: 'smart-garden-dc114',
    storageBucket: 'smart-garden-dc114.firebasestorage.app',
    iosClientId: '397847296748-vchtmm3q1ul3bpp0jg2v9kcektvlpi0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvOsgqdhaBxqHlh0BpeaHdYGrx-OWGmp0',
    appId: '1:397847296748:web:c55b4ecc035e116666c3c9',
    messagingSenderId: '397847296748',
    projectId: 'smart-garden-dc114',
    authDomain: 'smart-garden-dc114.firebaseapp.com',
    storageBucket: 'smart-garden-dc114.firebasestorage.app',
    measurementId: 'G-CE21SZ9TM9',
  );
}
